[build]
  publish = "build"
command = "npm run build"
  
# Rewrite API requests to actual location of serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Catch all other requests that don't match a file
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Set the default header to the one we want for documents
  for = "/*"
    [headers.values]
    cache-control = "public,max-age=86500"

[[headers]]
  # Override cache duration for assets with periods in the filename (i.e. static assets)
  for = "/*.*"
    [headers.values]
    cache-control = "public,max-age=8650000"